[package]
name = "rust_wheel"
version = "0.1.0"
edition = "2018"
license = "MIT"
authors = ["Jiangxiaoqiang <jiangtingqiang@gmail.com>"]
description = "A project to define some public component."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = { version = "1.0.64", features = ["derive"] }
config = "0.11"
diesel = { version = "1.4.7", features = ["postgres"] }
chrono = "0.4"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4"
