[package]
name = "rust_wheel"
version = "0.1.0"
edition = "2018"
license = "MIT"
authors = ["Jiangxiaoqiang <jiangtingqiang@gmail.com>"]
description = "A project to define some public component."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
